# Category
category:
    pattern: /category/(type)(/id)
    controller: Category
    extra:
        layout: category
        active:
            mainmenu: categories

# Categories
categories:
    pattern: /categories/(type)(/page)
    controller: Categories
    action:
        post: CopyController
        patch: BatchController
        put: FilterController
    extra:
        layout: categories
        active:
            mainmenu: categories

# Article
article:
    pattern: /article(/id)
    controller: Article
    extra:
        layout: article
        active:
            mainmenu: articles

# Articles
articles:
    pattern: /articles(/page)
    controller: Articles
    action:
        post: CopyController
        patch: BatchController
        put: FilterController
    extra:
        layout: articles
        active:
            mainmenu: articles

# Tag
tag:
    pattern: /tag(/id)
    controller: Tag
    extra:
        layout: tag
        active:
            mainmenu: tags

# Tags
tags:
    pattern: /tags(/page)
    controller: Tags
    action:
        post: CopyController
        patch: BatchController
        put: FilterController
    extra:
        layout: tags
        active:
            mainmenu: tags

# Comment
comment:
    pattern: /comment/(type)(/id)
    controller: Comment
    extra:
        layout: comment
        active:
            mainmenu: comments

# Comments
comments:
    pattern: /comments/(type)(/page)
    controller: Comments
    action:
        post: CopyController
        patch: BatchController
        put: FilterController
    extra:
        layout: comments
        active:
            mainmenu: comments

# Language
language:
    pattern: /language(/id)
    controller: Language
    extra:
        layout: language
        active:
            mainmenu: languages

# Languages
languages:
    pattern: /languages(/page)
    controller: Languages
    action:
        post: CopyController
        patch: BatchController
        put: FilterController
    extra:
        layout: languages
        active:
            mainmenu: languages

# Module
module:
    pattern: /module(/id)
    controller: Module
    extra:
        layout: module
        active:
            mainmenu: modules

# Modules
modules:
    pattern: /modules(/page)
    controller: Modules
    action:
        post: CopyController
        patch: BatchController
        put: FilterController
    extra:
        layout: modules
        active:
            mainmenu: modules

# Contact
contact:
    pattern: /contact(/id)
    controller: Contact
    extra:
        layout: contact
        menu:
            mainmenu: contacts

contact_preview:
    pattern: /contact-preview
    controller: Contact
    extra:
        format: json

# Contacts
contacts:
    pattern: /contacts(/page)
    controller: Contacts
    action:
        post: CopyController
        patch: BatchController
        put: FilterController
    extra:
        layout: contacts
        menu:
            mainmenu: contacts

# Page
page:
    pattern: /page(/id)
    controller: Page
    extra:
        layout: page
        menu:
            mainmenu: pages

# Pages
pages:
    pattern: /pages(/page)
    controller: Pages
    action:
        post: CopyController
        patch: BatchController
        put: FilterController
    extra:
        layout: pages
        menu:
            mainmenu: pages

# Luna
_luna_img_upload:
    pattern: /_luna/image/upload
    controller: Luna
    action:
        post|put|patch: ImageUploadController

_luna_ajax_tags:
    pattern: /_luna/ajax/tags
    controller: Lyrasoft\Luna\Admin\Controller\Luna\Ajax
    action:
        get: TagsGetController

_luna_ajax_tag:
    pattern: /_luna/ajax/tag
    controller: Lyrasoft\Luna\Admin\Controller\Luna\Ajax
    action:
        post|put|patch: TagSaveController
