
table:
    categories: categories
    articles: articles
    tags: tags
    content_tag_maps: content_tag_maps

frontend:
    package: front
    view:
        extends: _global.html
    language:
        prefix: merlin.

admin:
    package: admin
    view:
        extends: _global.admin.admin
    language:
        prefix: merlin.
