
# Article
article:
    pattern: /post/(id)-(alias)
    controller: Article
    requirements:
        id:
            \d+
    extra:
        layout: article
        category:
            type: article
        active:
            manimenu: articles

# Category
article_category:
    pattern: /category/(*path)
    controller: Category
    requirements:
        page: \d+
    extra:
        layout: category
        category:
            type: article
            repository: Articles
            view: Category
            ordering: article.created
            direction: DESC
            deep: true
        active:
            manimenu: category

# Tag
article_tag:
    pattern: /article-tag/(tag)(/page)
    controller: Category
    extra:
        layout: category
        category:
            type: article
        active:
            manimenu: tag

# Language
change_language:
    pattern: /language/checkout/(lang)
    controller: Language
    action:
        '*': ChangeController

# Contact
contact:
    pattern: /contact
    controller: Contact
    extra:
        layout: contact
        active:
            mainmenu: contact
