
# Article
article:
    pattern: /post/(id)-(alias)
    controller: Article
    requirements:
        id:
            \d+
    extra:
        layout: article
        category:
            type: article
        active:
            manimenu: articles

# Category
article_category:
    pattern: /category/(*path)
    controller: Category
    requirements:
        page: \d+
    extra:
        layout: category
        category:
            type: article
            repository: Articles
            view: Category
            ordering: article.created
            direction: DESC
            deep: true
        active:
            manimenu: category

# Tag
article_tag:
    pattern: /article-tag/(tag)(/page)
    controller: Category
    extra:
        layout: category
        category:
            type: article
        active:
            manimenu: tag

# Page
page_root:
    pattern: /page
    controller: Page
    extra:
        layout: page
        active:
            mainmenu: pages
page:
    pattern: /page/(*path)
    controller: Page
    extra:
        layout: page
        active:
            mainmenu: pages

# Pages
#pages:
#    pattern: /pages(/page)
#    controller: Pages
#    extra:
#        layout: pages
#        active:
#            mainmenu: pages

# Language
change_language:
    pattern: /language/checkout/(lang)
    controller: Language
    action:
        '*': ChangeController

# Contact
contact:
    pattern: /contact
    controller: Contact
    extra:
        layout: contact
        active:
            mainmenu: contact

# Captcha
_captcha_image:
    pattern: /_captcha/image
    controller: Captcha
    action:
        '*': CaptchaImageController
